INSERT INTO `tbcourse` (`id`, `cno`, `tno`, `cname`, `ccredit`, `cdescribe`, `cday`, `ctime`) VALUES (1, 'C01', 'T01', '高等数学', 3.0, '高等数学上', 1, 1);
INSERT INTO `tbcourse` (`id`, `cno`, `tno`, `cname`, `ccredit`, `cdescribe`, `cday`, `ctime`) VALUES (2, 'C02', 'T02', 'C语言程序设计', 3.0, 'c语言', 2, 2);
INSERT INTO `tbcourse` (`id`, `cno`, `tno`, `cname`, `ccredit`, `cdescribe`, `cday`, `ctime`) VALUES (4, 'C03', 'T02', '计算机网络', 3.0, '计网12345', 3, 1);
INSERT INTO `tbcourse` (`id`, `cno`, `tno`, `cname`, `ccredit`, `cdescribe`, `cday`, `ctime`) VALUES (5, 'C04', 'T01', '数据结构', 5.0, '数据结构与算法C++', 4, 2);
INSERT INTO `tbcourse` (`id`, `cno`, `tno`, `cname`, `ccredit`, `cdescribe`, `cday`, `ctime`) VALUES (7, 'C05', 'T01', '计算机操作系统', 4.0, '123456', 5, 3);
INSERT INTO `tbcourse` (`id`, `cno`, `tno`, `cname`, `ccredit`, `cdescribe`, `cday`, `ctime`) VALUES (11, 'C06', 'T02', '概率论', 3.0, '123', 3, 2);
INSERT INTO `tbcourse` (`id`, `cno`, `tno`, `cname`, `ccredit`, `cdescribe`, `cday`, `ctime`) VALUES (26, 'C07', 'T02', '数据库', 4.0, '123', 4, 4);
INSERT INTO `tbcourse` (`id`, `cno`, `tno`, `cname`, `ccredit`, `cdescribe`, `cday`, `ctime`) VALUES (27, 'C08', 'T01', '数据库', 4.0, '1234', 4, 4);
INSERT INTO `tbcourse` (`id`, `cno`, `tno`, `cname`, `ccredit`, `cdescribe`, `cday`, `ctime`) VALUES (28, 'C09', 'T01', '编译技术', 4.5, '编译', 3, 5);
